fields:
  report_date: "Date Rptd"
  occurrence_date: "DATE OCC"
  occurrence_time: "TIME OCC"
  area: "AREA NAME"
  crime_type: "Crm Cd Desc"
  crime_code_1: "Crm Cd 1"
  crime_code_2: "Crm Cd 2"
  crime_code_3: "Crm Cd 3"
  crime_code_4: "Crm Cd 4"
  premises: "Premis Desc"
  location: "LOCATION"
  nearby_cross_street: "Cross Street"
  victim_age: "Vict Age"
  victim_sex: "Vict Sex"
  weapon: "Weapon Desc"